### PR TITLE
Fixed date handling on forecasts

### PR DESCRIPTION
**Pull request by ciejer**

### CODE REVIEW

**Comment by droopanu** [comment]
Awesome! Hourly forecast looks much better.
Can you please also fix it for daily forecasts? :)

**Comment by ciejer** [comment]
> Awesome! Hourly forecast looks much better.
> Can you please also fix it for daily forecasts? :)

Hey @droopanu - I checked this out with your trigger template while working on 0.5.0, and it all formatted correctly on mine - can you be more specific please?

Hourly and daily use the same code for formatting dates so it should have fixed both (and did on mine)

**Comment by droopanu** [comment]
Hi @ciejer that is weird. Just testing with 0.5.0, I have the following sensor created:
```
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
      - platform: event
        event_type: event_template_reloaded
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.the_villa_metservice
        response_variable: forecast
    sensor:
      - name: MetService Weather Forecast Daily
        unique_id: metservice_forecast_daily
        state: "{{ now().isoformat() }}"
        attributes:
          temperature_0: "{{ forecast['weather.the_villa_metservice'].forecast[0].temperature | round(1) }}"
          templow_0: "{{ forecast['weather.the_villa_metservice'].forecast[0].templow | round(1) }}"
          condition_0: "{{ forecast['weather.the_villa_metservice'].forecast[0].condition  }}"
          temperature_1: "{{ forecast['weather.the_villa_metservice'].forecast[1].temperature | round(1) }}"
          templow_1: "{{ forecast['weather.the_villa_metservice'].forecast[1].templow | round(1) }}"
          condition_1: "{{ forecast['weather.the_villa_metservice'].forecast[1].condition  }}"
          forecast: "{{ forecast['weather.the_villa_metservice'].forecast }}"
```

And I'm getting this result:
image

**Comment by ciejer** [comment]
That's especially weird... here's my screenshot from running the same code (renamed to use my entity ids but nothing else)
image

**Comment by ciejer** [comment]
ah you're on mobile? Just crossed my mind you might not be on public api, tested, and found it not working there.

Looking for the fix now, shouldn't take long

**Comment by ciejer** [comment]
@droopanu try v0.5.1 :) sorry for confusion

**Comment by droopanu** [comment]
Looks awesome. Thank you very much

**Pull request merged**
